config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path

from django.shortcuts import render
from . import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='Home'),
    path('Home', views.home_page_view, name='Home'),
    path('Template2', views.page_one_view, name='Template2'),
    path('Template3', views.page_two_view, name='Template3')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
#  hello/views.py
import datetime
from django.shortcuts import render

def home_page_view(request):
	context = {'time' : datetime.datetime.now()}
	return render(request, 'website/Home.html', context)

def page_one_view(request):
    return render(request, 'website/Template 2.html')


def page_two_view(request):
    return render(request, 'website/Template 3.html')

website/templates/website/Home.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>Home</h3>
    <p>Laboratório 6 - Home</p>
{% endblock %}

website/templates/website/Template 2.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>Template 2</h3>
    <p>Laboratório 6 - PW </p>
{% endblock %}

website/templates/website/Template 3.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>Template 3</h3>
    <p>Laboratório 6 - PW</p>
{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
</head>
<body>
 <header class="jumbotron text-center">
        <h1>Laboratório 6: primeira web app django ⛅</h1>
        <p>laboratório 6</p>
        <nav>
            <a class="btn btn-info" href="{% url 'website:Home' %}">Home</a>
            <a class="btn btn-info" href="{% url 'website:Template2' %}">Template2</a>
            <a class="btn btn-info" href="{% url 'website:Template3' %}">Template3</a>
        </nav>
 </header>

    <article class="container">
        <main class="col-sm-6">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/images/imgLab6.png' %}">
        </aside>
    </article>

    <footer>
        Laboratório 6 - PW
    </footer>
</body>
</html>